"""Repository layer for Sketchy data persistence."""
from __future__ import annotations

from app.repositories.interfaces import (
    AccountAlreadyClaimedError,
    GameDetail,
    GameHistoryRepository,
    GameParticipantInput,
    GameParticipantSummary,
    GameRecordInput,
    GameSummary,
    InvalidProfileDataError,
    RepositoryError,
    RoundDetail,
    RoundGuessDetail,
    RoundGuessInput,
    RoundRecordInput,
    UserCredentials,
    UserData,
    UserRepository,
    UserStats,
    UsernameTakenError,
    WordListRepository,
    WordListSummary,
    WordPickTotals,
    WordStatsSummary,
    WordUsage,
)
from app.repositories.sqlalchemy import (
    SqlAlchemyGameHistoryRepository,
    SqlAlchemyUserRepository,
    SqlAlchemyWordListRepository,
)

__all__ = [
    "AccountAlreadyClaimedError",
    "GameDetail",
    "GameHistoryRepository",
    "GameParticipantInput",
    "GameParticipantSummary",
    "GameRecordInput",
    "GameSummary",
    "InvalidProfileDataError",
    "RepositoryError",
    "RoundDetail",
    "RoundGuessDetail",
    "RoundGuessInput",
    "RoundRecordInput",
    "SqlAlchemyGameHistoryRepository",
    "SqlAlchemyUserRepository",
    "SqlAlchemyWordListRepository",
    "UserCredentials",
    "UserData",
    "UserRepository",
    "UserStats",
    "UsernameTakenError",
    "WordListRepository",
    "WordListSummary",
    "WordPickTotals",
    "WordStatsSummary",
    "WordUsage",
]
