"""Repository layer for Sketchy data persistence."""
from __future__ import annotations

from app.repositories.interfaces import (
    AccountAlreadyClaimedError,
    GameDetail,
    GameHistoryRepository,
    GameParticipantInput,
    GameParticipantSummary,
    GameRecordInput,
    GameSummary,
    InvalidProfileDataError,
    RepositoryError,
    TurnDetail,
    TurnGuessDetail,
    TurnGuessInput,
    TurnRecordInput,
    UserCredentials,
    UserData,
    UserRepository,
    UserStats,
    UsernameTakenError,
    PromptListRepository,
    PromptListSummary,
    WordPickTotals,
    WordStatsSummary,
    WordUsage,
)
from app.repositories.sqlalchemy import (
    SqlAlchemyGameHistoryRepository,
    SqlAlchemyUserRepository,
    SqlAlchemyPromptListRepository,
)

__all__ = [
    "AccountAlreadyClaimedError",
    "GameDetail",
    "GameHistoryRepository",
    "GameParticipantInput",
    "GameParticipantSummary",
    "GameRecordInput",
    "GameSummary",
    "InvalidProfileDataError",
    "RepositoryError",
    "TurnDetail",
    "TurnGuessDetail",
    "TurnGuessInput",
    "TurnRecordInput",
    "SqlAlchemyGameHistoryRepository",
    "SqlAlchemyUserRepository",
    "SqlAlchemyPromptListRepository",
    "UserCredentials",
    "UserData",
    "UserRepository",
    "UserStats",
    "UsernameTakenError",
    "PromptListRepository",
    "PromptListSummary",
    "WordPickTotals",
    "WordStatsSummary",
    "WordUsage",
]
