// Derives the shipping brand art from the authored logo.
//
// Source of truth: scripts/brand/sketchy-logo-source.svg — Stefano's Inkscape
// original, kept verbatim so the derivation is always auditable.
//
// Paths are matched by ROLE, not by id: Inkscape renumbers ids on every
// re-export, so keying off them breaks each time the logo is redrawn.
//   gradient fill   -> the lettering, S-tail and brush tip
//   solid orange    -> the brush swoosh
//   #999999         -> the ferrule stripes
//
// Shipping swaps those literals for theme tokens so one mark serves both
// themes. Geometry is copied through untouched.
//
// Run:  node scripts/brand/derive-assets.mjs
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..", "..");
const source = readFileSync(join(here, "sketchy-logo-source.svg"), "utf8");

const FERRULE_FILL = "#999999";
const found = { lettering: [], swoosh: [], ferrule: [] };

for (const m of source.matchAll(/<path\b([\s\S]*?)\/>/g)) {
  const attrs = m[1];
  const d = attrs.match(/\sd="([^"]+)"/)?.[1];
  const fill = attrs.match(/fill:\s*([^;"]+)/)?.[1]?.trim();
  if (!d || !fill) continue;
  const path = d.replace(/\s+/g, " ").trim();
  if (fill.startsWith("url(")) found.lettering.push(path);
  else if (fill.toLowerCase() === FERRULE_FILL) found.ferrule.push(path);
  else found.swoosh.push(path);
}

if (found.lettering.length !== 1) {
  throw new Error(`expected exactly one gradient-filled lettering path, found ${found.lettering.length}`);
}
if (found.swoosh.length !== 1) {
  throw new Error(`expected exactly one solid-coloured swoosh path, found ${found.swoosh.length}`);
}
if (found.ferrule.length !== 2) {
  throw new Error(`expected two ${FERRULE_FILL} ferrule stripes, found ${found.ferrule.length}`);
}

const g = source.match(/x1="([\d.]+)"\s+y1="([\d.]+)"\s+x2="([\d.]+)"\s+y2="([\d.]+)"/);
if (!g) throw new Error("could not read the lettering gradient vector");
const [, x1, y1, x2, y2] = g.map((v) => (typeof v === "string" ? Number(v).toFixed(2) : v));

// Tight bbox of all four paths together, measured in a browser via getBBox().
// Node has no bezier bbox maths, so this cannot be recomputed here. If a
// re-export ever moves the artwork on its 1448x724 canvas, re-measure with:
//   <svg viewBox="0 0 1448 724"><g id="g">…the four paths…</g></svg>
//   document.getElementById('g').getBBox()
// Verified unchanged across the 2026-08-26 re-exports.
const BOX = { x: 138.02, y: 177.12, w: 1170.69, h: 371.69 };
const viewBox = `${BOX.x} ${BOX.y} ${BOX.w} ${BOX.h}`;
const aspect = (BOX.w / BOX.h).toFixed(4);

const header = `// GENERATED by scripts/brand/derive-assets.mjs — do not edit by hand.
// Source artwork: scripts/brand/sketchy-logo-source.svg
//
// Geometry is the authored logo, untouched. Only the paint is swapped for
// theme tokens: the lettering fades from --ink into --warm exactly as the
// source gradient does, so the mark reads correctly on paper and on slate
// without needing a second variant.`;

writeFileSync(
  join(repo, "frontend", "src", "components", "brandArt.ts"),
  `${header}

/** Tight bounding box of all four paths, measured with getBBox(). */
export const WORDMARK_VIEWBOX = "${viewBox}";

/** Width / height of the artwork, for deriving one axis from the other. */
export const WORDMARK_ASPECT = ${aspect};

/** Gradient vector, in the same user space as the paths. */
export const LETTERING_GRADIENT = { x1: "${x1}", y1: "${y1}", x2: "${x2}", y2: "${y2}" } as const;

/** The brush swoosh. Painted --warm. */
export const SWOOSH_PATH =
  "${found.swoosh[0]}";

/** Lettering, S-tail and brush tip. Painted with the --ink -> --warm gradient. */
export const LETTERING_PATH =
  "${found.lettering[0]}";

/** The two ferrule stripes. Painted --line-strong, which inverts per theme. */
export const FERRULE_PATHS = [
${found.ferrule.map((d) => `  "${d}",`).join("\n")}
] as const;
`,
);

// The mockups in docs/ui-mockups keep a parallel wordmark helper; feed it from
// the same source so the artboards can never drift from the app.
writeFileSync(
  join(repo, "docs", "ui-mockups", "tools", "brandArt.mjs"),
  `${header}
export const WORDMARK_VIEWBOX = "${viewBox}";
export const WORDMARK_ASPECT = ${aspect};
export const LETTERING_GRADIENT = { x1: "${x1}", y1: "${y1}", x2: "${x2}", y2: "${y2}" };
export const SWOOSH_PATH =
  "${found.swoosh[0]}";
export const LETTERING_PATH =
  "${found.lettering[0]}";
export const FERRULE_PATHS = [
${found.ferrule.map((d) => `  "${d}",`).join("\n")}
];
`,
);

console.log(`viewBox ${viewBox}   aspect ${aspect}`);
console.log(`  lettering ${found.lettering[0].length} chars`);
console.log(`  swoosh    ${found.swoosh[0].length} chars`);
console.log(`  ferrule   ${found.ferrule.map((d) => d.length).join(", ")} chars`);
console.log(`  gradient  ${x1},${y1} -> ${x2},${y2}`);
console.log("wrote frontend/src/components/brandArt.ts");
console.log("wrote docs/ui-mockups/tools/brandArt.mjs");

/* ---------------------------------------------------------------- app icon */
// scripts/brand/sketchy-icon-source.svg is the authored square mark. It is
// rewritten rather than re-authored: every path, transform and gradient is
// passed through untouched and only the paint is lifted into a <style> block,
// so the file can respond to prefers-color-scheme.
//
// A file-based icon gets no CSS context — <link rel="icon"> and <img> render
// it in an isolated document, so var() and currentColor do not resolve. Hence
// literal colours plus an internal media query rather than theme tokens.
//
// The dark values are derived from the light ones by preserving each element's
// authored contrast relationship, not by eye:
//
//   element   light                  ratio   dark                   ratio
//   S         #1a1a1a on paper       16.16   #f8fafc on slate       17.06
//   handle    #784421 on paper        7.36   #d29b6a on slate        7.34
//   ferrule   #999999 on handle       2.78   #7a5636 on handle       2.69
//   swoosh    #ff7f2a unchanged — 2.34 on paper, 7.07 on slate
//
// Without this the mark is unreadable on a dark tab bar: the authored S sits
// at 1.03:1 against #0f172a.
// Home-screen icons sit on a dark ground on purpose. iOS draws no border or
// shadow, so the icon's own ground is its silhouette — a paper-white tile
// dissolves into a light wallpaper, and the orange only carries 2.34:1 on
// paper against 7.07:1 here.
//
// This is --paper's dark value from theme.css. Repeated as a literal because a
// rasterised PNG has no CSS context; if the dark ground ever changes, change it
// here too.
const ICON_GROUND = "#0f172a";

const iconSource = readFileSync(join(here, "sketchy-icon-source.svg"), "utf8");

const PAINT = [
  [/style="fill:#999999"/g, 'class="fer"', 2],
  [/style="fill:#784421;fill-opacity:1"/g, 'class="handle"', 1],
  [/style="fill:#ff7f2a"/g, 'class="swoosh"', 1],
  [/style="fill:url\(#linearGradient1\);fill-opacity:1"/g, 'class="letter"', 1],
  [/style="stop-color:#1a1a1a;stop-opacity:1;"/g, 'class="stopA"', 1],
  [/style="stop-color:#ff7f2a;stop-opacity:1;"/g, 'class="stopB"', 1],
];

let icon = iconSource;
for (const [re, cls, expected] of PAINT) {
  const hits = (icon.match(re) || []).length;
  if (hits !== expected) {
    throw new Error(`icon: expected ${expected} match for ${re}, found ${hits} — re-export changed the paint`);
  }
  icon = icon.replace(re, cls);
}

// Square the canvas: the art is 403.69 x 371.57, so pad the short axis rather
// than cropping. Favicon and apple-touch slots are square.
const ICON_W = 403.69119, ICON_H = 371.5726;
const yOff = ((ICON_W - ICON_H) / 2).toFixed(2);

// The favicon carries the dark treatment on its own rounded tile rather than
// adapting to prefers-color-scheme. A dark tile is a legible object on light
// AND dark browser chrome, whereas a transparent mark needs the ground to
// cooperate — and it keeps the favicon identical to the home-screen icon.
// Handle #d29b6a, bands #94a3b8 — the site's dark --brand-ferrule, so the icon
// and the in-app wordmark use the literal same value.
//
// Noted deliberately: #94a3b8 on #d29b6a is 1.05:1, so the bands read as a
// soft tonal break in the handle rather than as distinct stripes. That is the
// intended look — do not "fix" the contrast here without asking.
const ICON_STYLE = `<style>
    .letter{fill:url(#linearGradient1)}
    .swoosh{fill:#ff7f2a}
    .handle{fill:#d29b6a}
    .fer{fill:#94a3b8}
    .stopA{stop-color:#f8fafc}
    .stopB{stop-color:#ff7f2a}
  </style>`;

// Tile: the mark is inset so it does not touch the corners, and the radius is
// the design system's proportion (--radius on a 48px control), so the favicon
// reads as the same family as the app's own surfaces.
const FAVICON_INSET = 0.08;
const favPad = ICON_W * FAVICON_INSET;
const favBox = ICON_W + favPad * 2;
const favTile = `<rect x="${(-favPad).toFixed(2)}" y="${(-favPad - Number(yOff)).toFixed(2)}"`
  + ` width="${favBox.toFixed(2)}" height="${favBox.toFixed(2)}"`
  + ` rx="${(favBox * 0.30).toFixed(2)}" fill="${ICON_GROUND}"/>`;

icon = icon
  .replace(/<\?xml[^>]*\?>\s*/, "")
  .replace(/\s+(?:inkscape|sodipodi):[\w-]+="[^"]*"/g, "")
  .replace(/\s+xmlns:(?:inkscape|sodipodi)="[^"]*"/g, "")
  .replace(/<sodipodi:namedview[\s\S]*?\/>/g, "")
  .replace(/\s+xml:space="preserve"/g, "")
  .replace(/width="[\d.]+"\s*height="[\d.]+"\s*viewBox="[^"]*"/,
           `width="${favBox.toFixed(0)}" height="${favBox.toFixed(0)}"`
           + ` viewBox="${(-favPad).toFixed(2)} ${(-favPad - Number(yOff)).toFixed(2)} ${favBox.toFixed(2)} ${favBox.toFixed(2)}"`)
  .replace("<defs", `${ICON_STYLE}<defs`)
  .replace(/(<g\b[^>]*>)/, `${favTile}$1`)
  .replace(/\n\s*\n/g, "\n");

writeFileSync(join(repo, "frontend", "public", "favicon.svg"), icon.trim() + "\n");
console.log(`wrote frontend/public/favicon.svg (${icon.length} bytes)`);

/* ------------------------------------------------------- raster icon sources */
// PNGs cannot carry a media query, and iOS ignores alpha on apple-touch-icon
// (it composites onto black), so the raster variants are baked opaque on the
// light ground with the authored colours. These are intermediates: they are
// written to scripts/brand/raster/ and rasterised by render-rasters.sh.
const BAKED_PAINT = `<style>
    .letter{fill:url(#linearGradient1)}
    .swoosh{fill:#ff7f2a}
    .handle{fill:#d29b6a}
    .fer{fill:#94a3b8}
    .stopA{stop-color:#f8fafc}
    .stopB{stop-color:#ff7f2a}
  </style>`;

// `icon` still carries the themed <style>; swap it for the baked one and add
// an opaque ground. `inset` is the fraction of the tile left as margin.
function rasterIcon(inset) {
  const side = ICON_W;
  const pad = side * inset;
  const box = side + pad * 2;
  return icon
    .replace(/<style>[\s\S]*?<\/style>/, BAKED_PAINT)
    .replace(/viewBox="[^"]*"/, `viewBox="${-pad.toFixed(2)} ${(-pad - Number(yOff)).toFixed(2)} ${box.toFixed(2)} ${box.toFixed(2)}"`)
    .replace(/(<svg[^>]*>)/, `$1<rect x="${-pad.toFixed(2)}" y="${(-pad - Number(yOff)).toFixed(2)}" width="${box.toFixed(2)}" height="${box.toFixed(2)}" fill="${ICON_GROUND}"/>`);
}

mkdirSync(join(here, "raster"), { recursive: true });
writeFileSync(join(here, "raster", "icon-square.svg"), rasterIcon(0.10));
// Maskable icons are cropped to an inner circle by the OS; keep the mark well
// inside the 80% safe zone.
writeFileSync(join(here, "raster", "icon-maskable.svg"), rasterIcon(0.28));

// The social card is a composition, not a resize: the lockup centred on the
// dark ground, sized so the 1200x630 crop still leaves it room to breathe.
const OG_BG = "#0f172a", OG_INK = "#f8fafc", OG_WARM = "#ee7e48", OG_FER = "#94a3b8";
const lockW = 820, lockH = Math.round(lockW / Number(aspect));

writeFileSync(
  join(here, "raster", "og-image.svg"),
  `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
  <rect width="1200" height="630" fill="${OG_BG}"/>
  <g transform="translate(${((1200 - lockW) / 2).toFixed(1)} ${((630 - lockH) / 2).toFixed(1)})">
    <svg width="${lockW}" height="${lockH}" viewBox="${viewBox}">
      <defs><linearGradient id="og" gradientUnits="userSpaceOnUse" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}">
        <stop offset="0" stop-color="${OG_INK}"/><stop offset="1" stop-color="${OG_WARM}"/>
      </linearGradient></defs>
      <path d="${found.swoosh[0]}" fill="${OG_WARM}"/>
      <path d="${found.lettering[0]}" fill="url(#og)"/>
${found.ferrule.map((d) => `      <path d="${d}" fill="${OG_FER}"/>`).join("\n")}
    </svg>
  </g>
</svg>
`,
);
console.log("wrote scripts/brand/raster/{icon-square,icon-maskable,og-image}.svg");

/* --------------------------------------------------------- not-found doodle */
// ------------------------------------------------------------- the doodles
//
// Two drawings hang on a canvas sheet: the hand-drawn 404 on the not-found page
// (scripts/brand/sketchy-404-source.svg - numerals, a swash, four sparks) and
// the ladybird on the crash page (scripts/brand/sketchy-bug-source.svg).
//
// They are painted in literal colours rather than theme tokens, because each is
// a drawing *on the canvas* - and `.canvas-stack` is a white sheet in both
// themes, so ink chosen to respond to the theme would only get weaker on the
// one ground it ever sits on. The sources' flat RGB primaries are the author's
// placeholders; each maps to the same-family swatch from COLOR_PAIRS in
// frontend/src/lib/drawingRules.ts, which is what a player would have had to
// hand - except the yellow spark, which is Stefano's own brighter yellow.
//
// Matched by ROLE - the fill literal - and not by id, for the same reason the
// logo is: Inkscape renumbers ids on every re-export.
const PALETTE = {
  black: "#000000",
  white: "#ffffff",
  red: "#ed1c24",
  orange: "#ff7f27",
  green: "#22b14c",
  sky: "#7ac9e8",
  blue: "#3f48cc",
};

function deriveDoodle({ label, sourceFile, paint, expected, constPrefix, tsFile, mjsFile }) {
  const source = readFileSync(join(here, sourceFile), "utf8");
  const paths = [];
  const seen = {};

  for (const m of source.matchAll(/<path\b([\s\S]*?)\/>/g)) {
    const attrs = m[1];
    const d = attrs.match(/\sd="([^"]+)"/)?.[1];
    const fill = attrs.match(/fill:\s*([^;"]+)/)?.[1]?.trim().toLowerCase();
    if (!d || !fill) continue;
    const colour = paint[fill];
    if (!colour) throw new Error(`${label}: no palette mapping for the authored fill ${fill}`);
    seen[fill] = (seen[fill] ?? 0) + 1;
    paths.push({ d: d.replace(/\s+/g, " ").trim(), fill: colour });
  }

  for (const [fill, count] of Object.entries(expected)) {
    if (seen[fill] !== count) {
      throw new Error(`${label}: expected ${count} path(s) filled ${fill}, found ${seen[fill] ?? 0} - a re-export changed the paint`);
    }
  }

  // The artwork sits inside one translated layer. Baking that translate into
  // the viewBox origin is exactly equivalent and leaves the paths untouched, so
  // the shipped component is a flat list of paths with no wrapper transform.
  const shift = source.match(/transform="translate\(([-\d.]+),([-\d.]+)\)"/g);
  if (!shift || shift.length !== 1) {
    throw new Error(`${label}: expected exactly one translated layer, found ${shift?.length ?? 0}`);
  }
  const [, dx, dy] = source.match(/transform="translate\(([-\d.]+),([-\d.]+)\)"/);
  const [, dw, dh] = source.match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/);
  const viewBox = `${-Number(dx)} ${-Number(dy)} ${dw} ${dh}`;

  const header = `// GENERATED by scripts/brand/derive-assets.mjs — do not edit by hand.
// Source artwork: scripts/brand/${sourceFile}
//
// Geometry is the authored drawing, untouched; the layer's translate is baked
// into the viewBox origin instead. The paint is the game's drawing palette,
// not theme tokens: this hangs on the canvas sheet, which is white in both
// themes.`;

  const entries = paths
    .map(({ d, fill }) => `  { fill: "${fill}", d: "${d}" },`)
    .join("\n");

  writeFileSync(
    join(repo, "frontend", "src", "components", tsFile),
    `${header}

/** The authored page box, with the layer translate folded into its origin. */
export const ${constPrefix}_VIEWBOX = "${viewBox}";

/** Every path in source order, each with the palette colour it is painted. */
export const ${constPrefix}_PATHS: readonly { fill: string; d: string }[] = [
${entries}
] as const;
`,
  );

  writeFileSync(
    join(repo, "docs", "ui-mockups", "tools", mjsFile),
    `${header}
export const ${constPrefix}_VIEWBOX = "${viewBox}";
export const ${constPrefix}_PATHS = [
${entries}
];
`,
  );

  console.log(`${label}: ${paths.length} paths, viewBox ${viewBox}`);
  console.log(`wrote frontend/src/components/${tsFile}`);
  console.log(`wrote docs/ui-mockups/tools/${mjsFile}`);
}

deriveDoodle({
  label: "404 art",
  sourceFile: "sketchy-404-source.svg",
  paint: {
    // numerals and swash: the palette's blue and orange.
    "#0000ff": PALETTE.blue,
    "#ff6600": PALETTE.orange,
    // sparks. Yellow is picked rather than taken from COLOR_PAIRS: chosen for
    // the drawing, and lighter than the palette's own #fff200.
    "#ff0000": PALETTE.red,
    "#ffff00": "#fbec5d",
    "#00ff00": PALETTE.green,
    "#00ffff": PALETTE.sky,
  },
  expected: { "#0000ff": 5, "#ff6600": 1, "#ff0000": 1, "#ffff00": 1, "#00ff00": 1, "#00ffff": 1 },
  constPrefix: "NOT_FOUND",
  tsFile: "notFoundArt.ts",
  mjsFile: "notFoundArt.mjs",
});

// The crash page's ladybird: red shell, black head, split, spots, legs and
// antennae, white eyes (the one place white ink shows, because it sits on the
// black head), an orange buzz trailing off, and three blue twitch marks. The
// counts pin the drawing's anatomy, so a re-export that drops a leg is caught.
deriveDoodle({
  label: "bug art",
  sourceFile: "sketchy-bug-source.svg",
  paint: {
    "#ff0000": PALETTE.red,
    "#000000": PALETTE.black,
    "#ffffff": PALETTE.white,
    "#ff6600": PALETTE.orange,
    "#0000ff": PALETTE.blue,
  },
  expected: { "#ff0000": 1, "#000000": 15, "#ffffff": 2, "#ff6600": 1, "#0000ff": 3 },
  constPrefix: "CRASH",
  tsFile: "crashArt.ts",
  mjsFile: "crashArt.mjs",
});
