// Derives the shipping brand art from the authored logo.
//
// Source of truth: scripts/brand/sketchy-logo-source.svg — Stefano's Inkscape
// original, kept verbatim so the derivation is always auditable.
//
// Paths are matched by ROLE, not by id: Inkscape renumbers ids on every
// re-export, so keying off them breaks each time the logo is redrawn.
//   gradient fill   -> the lettering, S-tail and brush tip
//   solid orange    -> the brush swoosh
//   #999999         -> the ferrule stripes
//
// Shipping swaps those literals for theme tokens so one mark serves both
// themes. Geometry is copied through untouched.
//
// Run:  node scripts/brand/derive-assets.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..", "..");
const source = readFileSync(join(here, "sketchy-logo-source.svg"), "utf8");

const FERRULE_FILL = "#999999";
const found = { lettering: [], swoosh: [], ferrule: [] };

for (const m of source.matchAll(/<path\b([\s\S]*?)\/>/g)) {
  const attrs = m[1];
  const d = attrs.match(/\sd="([^"]+)"/)?.[1];
  const fill = attrs.match(/fill:\s*([^;"]+)/)?.[1]?.trim();
  if (!d || !fill) continue;
  const path = d.replace(/\s+/g, " ").trim();
  if (fill.startsWith("url(")) found.lettering.push(path);
  else if (fill.toLowerCase() === FERRULE_FILL) found.ferrule.push(path);
  else found.swoosh.push(path);
}

if (found.lettering.length !== 1) {
  throw new Error(`expected exactly one gradient-filled lettering path, found ${found.lettering.length}`);
}
if (found.swoosh.length !== 1) {
  throw new Error(`expected exactly one solid-coloured swoosh path, found ${found.swoosh.length}`);
}
if (found.ferrule.length !== 2) {
  throw new Error(`expected two ${FERRULE_FILL} ferrule stripes, found ${found.ferrule.length}`);
}

const g = source.match(/x1="([\d.]+)"\s+y1="([\d.]+)"\s+x2="([\d.]+)"\s+y2="([\d.]+)"/);
if (!g) throw new Error("could not read the lettering gradient vector");
const [, x1, y1, x2, y2] = g.map((v) => (typeof v === "string" ? Number(v).toFixed(2) : v));

// Tight bbox of all four paths together, measured in a browser via getBBox().
// Node has no bezier bbox maths, so this cannot be recomputed here. If a
// re-export ever moves the artwork on its 1448x724 canvas, re-measure with:
//   <svg viewBox="0 0 1448 724"><g id="g">…the four paths…</g></svg>
//   document.getElementById('g').getBBox()
// Verified unchanged across the 2026-08-26 re-exports.
const BOX = { x: 138.02, y: 177.12, w: 1170.69, h: 371.69 };
const viewBox = `${BOX.x} ${BOX.y} ${BOX.w} ${BOX.h}`;
const aspect = (BOX.w / BOX.h).toFixed(4);

const header = `// GENERATED by scripts/brand/derive-assets.mjs — do not edit by hand.
// Source artwork: scripts/brand/sketchy-logo-source.svg
//
// Geometry is the authored logo, untouched. Only the paint is swapped for
// theme tokens: the lettering fades from --ink into --warm exactly as the
// source gradient does, so the mark reads correctly on paper and on slate
// without needing a second variant.`;

writeFileSync(
  join(repo, "frontend", "src", "components", "brandArt.ts"),
  `${header}

/** Tight bounding box of all four paths, measured with getBBox(). */
export const WORDMARK_VIEWBOX = "${viewBox}";

/** Width / height of the artwork, for deriving one axis from the other. */
export const WORDMARK_ASPECT = ${aspect};

/** Gradient vector, in the same user space as the paths. */
export const LETTERING_GRADIENT = { x1: "${x1}", y1: "${y1}", x2: "${x2}", y2: "${y2}" } as const;

/** The brush swoosh. Painted --warm. */
export const SWOOSH_PATH =
  "${found.swoosh[0]}";

/** Lettering, S-tail and brush tip. Painted with the --ink -> --warm gradient. */
export const LETTERING_PATH =
  "${found.lettering[0]}";

/** The two ferrule stripes. Painted --line-strong, which inverts per theme. */
export const FERRULE_PATHS = [
${found.ferrule.map((d) => `  "${d}",`).join("\n")}
] as const;
`,
);

// The mockups in docs/ui-mockups keep a parallel wordmark helper; feed it from
// the same source so the artboards can never drift from the app.
writeFileSync(
  join(repo, "docs", "ui-mockups", "tools", "brandArt.mjs"),
  `${header}
export const WORDMARK_VIEWBOX = "${viewBox}";
export const WORDMARK_ASPECT = ${aspect};
export const LETTERING_GRADIENT = { x1: "${x1}", y1: "${y1}", x2: "${x2}", y2: "${y2}" };
export const SWOOSH_PATH =
  "${found.swoosh[0]}";
export const LETTERING_PATH =
  "${found.lettering[0]}";
export const FERRULE_PATHS = [
${found.ferrule.map((d) => `  "${d}",`).join("\n")}
];
`,
);

console.log(`viewBox ${viewBox}   aspect ${aspect}`);
console.log(`  lettering ${found.lettering[0].length} chars`);
console.log(`  swoosh    ${found.swoosh[0].length} chars`);
console.log(`  ferrule   ${found.ferrule.map((d) => d.length).join(", ")} chars`);
console.log(`  gradient  ${x1},${y1} -> ${x2},${y2}`);
console.log("wrote frontend/src/components/brandArt.ts");
console.log("wrote docs/ui-mockups/tools/brandArt.mjs");
