"""Partition collected E2E cases across CI runners, then let xdist schedule them.

Cases are weighed by `e2e_durations.json` beside this module - the seconds each
took on a recent CI run, regenerated by `scripts/update-e2e-durations.py` from the
JUnit reports CI uploads. A case the file does not know gets the median weight, so
a new test is never left out and a stale file only costs balance, not coverage.
With no file at all every case weighs the same and the split is round-robin over
sorted IDs, which is what it was before the weights (#660).
"""
from __future__ import annotations

import json
import statistics
from pathlib import Path

import pytest

DURATIONS_FILE = Path(__file__).with_name("e2e_durations.json")


def shard_spec(value):
    try:
        index, total = map(int, value.split("/"))
    except ValueError as exc:
        raise pytest.UsageError("--e2e-shard must be INDEX/TOTAL (for example 1/2)") from exc
    if not 1 <= index <= total:
        raise pytest.UsageError("--e2e-shard requires 1 <= INDEX <= TOTAL")
    return index, total


def load_durations(path: Path = DURATIONS_FILE) -> dict[str, float]:
    try:
        return {nodeid: float(seconds) for nodeid, seconds in json.loads(path.read_text()).items()}
    except FileNotFoundError:
        return {}


def partition(nodeids, total: int, durations: dict[str, float]) -> dict[str, int]:
    """Assign every case to a shard (zero-based), the same way on every runner.

    Longest case first onto the lightest shard so far - the classic greedy
    bound, within a third of optimal, and deterministic: ties on weight go by
    ID and ties on load to the lower shard. With equal weights this is exactly
    round-robin over sorted IDs.
    """
    known = [durations[n] for n in nodeids if n in durations]
    fallback = statistics.median(known) if known else 1.0
    weight = {nodeid: durations.get(nodeid, fallback) for nodeid in nodeids}
    loads = [0.0] * total
    assignment = {}
    for nodeid in sorted(nodeids, key=lambda n: (-weight[n], n)):
        shard = min(range(total), key=lambda i: (loads[i], i))
        loads[shard] += weight[nodeid]
        assignment[nodeid] = shard
    return assignment


def pytest_addoption(parser):
    parser.addoption(
        "--e2e-shard", type=shard_spec, default=None,
        help="Run one INDEX/TOTAL partition of the collected test cases (one-based).",
    )


def pytest_report_header(config):
    shard = config.getoption("e2e_shard")
    if shard:
        return f"E2E shard: {shard[0]}/{shard[1]}"


@pytest.hookimpl(trylast=True)
def pytest_collection_modifyitems(config, items):
    shard = config.getoption("e2e_shard")
    if shard is None:
        return
    index, total = shard
    # Full node IDs include parametrizations, and every runner collects the
    # same ones, so they all compute the same split without a maintained
    # file list that can omit new tests.
    assignment = partition([item.nodeid for item in items], total, load_durations())
    selected = [item for item in items if assignment[item.nodeid] == index - 1]
    deselected = [item for item in items if assignment[item.nodeid] != index - 1]
    items[:] = selected
    config.hook.pytest_deselected(items=deselected)
