"""The dashboards are their generator's output, and name only real series (#968).

A panel whose metric was renamed under it draws an empty graph, and nobody
notices until the day it was needed - the reason R-OBS-13 keeps the alert rules
in the repository, and checks them, applies to a dashboard just the same. So
every query here is held to the same list of sources the alert rules are: the
server's own exposition, the recording rules, the probe's textfile, and the
exporters named once in `test_alert_rules.py`.

The JSON is generated by `ops/grafana/generate.py` and committed; hand-editing
it, or saving it from Grafana's UI, is caught by the first test.
"""
from __future__ import annotations

import importlib.util
import json
from pathlib import Path
import re
import sys

import yaml

from tests.test_alert_rules import (
    EXTERNAL_SERIES,
    RULE_FILES,
    exposed_names,
    load,
    rule_names,
)

GRAFANA = Path(__file__).resolve().parents[2] / "ops" / "grafana"


def generator():
    name = "sketchy_grafana_generate"
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(name, GRAFANA / "generate.py")
    module = importlib.util.module_from_spec(spec)
    # Registered first: `dataclasses` looks its own module up while building
    # each class, and a file loaded by path is otherwise nowhere to be found.
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def dashboards() -> dict[str, dict]:
    return {path.name: json.loads(path.read_text()) for path in sorted((GRAFANA / "dashboards").glob("*.json"))}


def test_the_committed_dashboards_are_the_generators_output():
    stale = generator().stale()
    assert stale == [], f"regenerate with `python3 ops/grafana/generate.py`: {stale}"


# What a query may name besides a series: PromQL's own vocabulary. Anything
# else an expression mentions has to be a series something exposes - checking
# only the `sketchy_`/`pg_` namespaces let `process_resident_memory_bytes`,
# the name a panel gets wrong by forgetting our prefix, through unread.
PROMQL_WORDS = frozenset(
    """
    and by bool group_left group_right ignoring offset on or unless without le quantile
    inf nan start end
    """.split()
)
# The functions and operators a query may call. A name stripped as a call is
# held to this too: `histogram_quantil(...)` is a panel Grafana refuses, and
# removing every `identifier(` would have taken it out unread.
PROMQL_CALLS = frozenset(
    """
    abs absent absent_over_time avg avg_over_time bottomk ceil changes clamp clamp_max
    clamp_min count count_over_time count_values day_of_month day_of_week day_of_year
    days_in_month delta deriv exp floor group histogram_count histogram_quantile
    histogram_sum holt_winters hour idelta increase irate label_join label_replace last_over_time
    ln log10 log2 max max_over_time min min_over_time minute month predict_linear
    present_over_time quantile quantile_over_time rate resets round scalar sgn sort
    sort_desc sqrt stddev stddev_over_time stdvar stdvar_over_time sum sum_over_time
    time timestamp topk vector year
    """.split()
)
# Operators that combine series, and so drop every label they were not told to
# keep. `topk` and `bottomk` select whole series and keep their labels.
AGGREGATIONS = "sum|avg|min|max|count|count_values|group|stddev|stdvar|quantile"
AGGREGATION = re.compile(rf"\b(?:{AGGREGATIONS})\b\s*(?:(by|without)\s*\(([^()]*)\))?")
LABEL_BLOCK = re.compile(r"\{[^{}]*\}")
GROUPING = re.compile(r"\b(?:by|without|ignoring|on|group_left|group_right)\s*\([^()]*\)")
WINDOW_LITERAL = re.compile(r"\[[^\[\]]*\]")
# Not inside a name: `sketchy:socket_p95_seconds:5m` is a rule, not a number.
NUMBER = re.compile(r"(?<![\w:])\d+(?:\.\d+)?(?:e[+-]?\d+)?(?:ms|[smhdwy])?\b", re.IGNORECASE)
CALL = re.compile(r"\b([a-zA-Z_:][a-zA-Z0-9_:]*)\s*\(")
IDENTIFIER = re.compile(r"[a-zA-Z_:][a-zA-Z0-9_:]*")


def _without_calls(expr: str) -> tuple[str, set[str]]:
    """The expression with its function calls removed, and their names."""
    # `sum by (transport) (...)` reads as a call to `by`; the vocabulary is
    # not what this is checking.
    called = set(CALL.findall(expr)) - PROMQL_WORDS
    return CALL.sub(" ", expr), called


def series_named(expr: str) -> set[str]:
    """Every series an expression reads, with labels, groupings, windows,
    numbers and function calls taken out first."""
    stripped = WINDOW_LITERAL.sub(" ", GROUPING.sub(" ", LABEL_BLOCK.sub(" ", expr)))
    stripped = NUMBER.sub(" ", _without_calls(stripped)[0])
    return {name for name in IDENTIFIER.findall(stripped) if name not in PROMQL_WORDS}


def labels_kept(expr: str) -> set[str] | None:
    """The labels an expression still carries, or None when it keeps them all.

    An aggregation combines series, so it keeps only what its `by` names -
    and the generator writes the prefix form, `sum by (transport) (...)`,
    which is why this cannot look for `sum(` alone."""
    kept: set[str] | None = None
    for clause, labels in AGGREGATION.findall(expr):
        named = {label.strip() for label in labels.split(",") if label.strip()}
        if clause == "by":
            kept = named if kept is None else kept | named
        elif clause == "without":
            continue  # keeps everything but `named`; no panel writes one yet
        else:
            # An aggregation with no grouping at all: one series out, no labels.
            return set() if kept is None else kept
    return kept


def windows_in(expr: str) -> set[str]:
    """Every range window the expression actually asks Prometheus for."""
    return {literal.strip("[]") for literal in WINDOW_LITERAL.findall(expr)}


def minutes(duration: str) -> float:
    """A PromQL duration in minutes, so windows and steps compare."""
    units = {"ms": 1 / 60000, "s": 1 / 60, "m": 1, "h": 60, "d": 1440, "w": 10080, "y": 525600}
    for unit in ("ms", "s", "m", "h", "d", "w", "y"):
        if duration.endswith(unit) and duration[: -len(unit)].isdigit():
            return int(duration[: -len(unit)]) * units[unit]
    raise AssertionError(f"not a duration: {duration}")


def test_every_series_a_panel_queries_is_one_something_exposes():
    known = exposed_names() | {name for path in RULE_FILES for name in rule_names(load(path))} | set(EXTERNAL_SERIES)
    unknown: dict[str, set[str]] = {}
    for dashboard, panel, expr in generator().expressions():
        missing = series_named(expr) - known
        missing |= _without_calls(expr)[1] - PROMQL_CALLS
        if missing:
            unknown[f"{dashboard} / {panel}"] = missing
    assert unknown == {}, unknown


def test_no_query_reaches_grafana_with_its_window_unresolved():
    """Queries are written with a placeholder for the rate window, and each
    dashboard's own window replaces it; one left behind is a broken panel."""
    placeholder = generator().WINDOW
    for _, panel, expr in generator().expressions():
        assert placeholder not in expr, panel
    for name, dashboard in dashboards().items():
        assert placeholder not in json.dumps(dashboard), name


def test_every_window_fits_inside_the_step_its_dashboard_opens_on():
    """Grafana's step is the range over about 800 points: at 7 d that is 10-15
    minutes, and a 5 m window inside it draws a third of the range and never
    looks at the rest. Read off the queries Grafana is actually sent, so a
    window written by hand is held to this too."""
    module = generator()
    opens_on = {dashboard.uid: dashboard.time_from for dashboard in module.DASHBOARDS}
    for uid, panel, expr in module.expressions():
        relative = opens_on[uid]
        assert relative.startswith("now-"), (uid, relative)
        step = minutes(relative.removeprefix("now-")) / 800
        for window in windows_in(expr):
            assert minutes(window) >= step, (uid, panel, window, relative)


def test_every_expression_nests_its_brackets():
    """The series check reads names, not syntax. `[5m)]` counts one of each
    and is still a query Grafana rejects at load."""
    closing = {")": "(", "]": "[", "}": "{"}
    for _, panel, expr in generator().expressions():
        stack: list[str] = []
        for character in expr:
            if character in "([{":
                stack.append(character)
            elif character in closing:
                assert stack and stack.pop() == closing[character], (panel, expr)
        assert not stack, (panel, expr)


def test_every_panel_is_a_kind_and_a_unit_grafana_knows():
    """A typo in either is silent: an unknown type renders "Panel plugin not
    found", an unknown unit quietly drops the formatting."""
    kinds = {"timeseries", "stat", "row"}
    units = {"short", "s", "bytes", "Bps", "reqps", "percentunit", "none"}
    for name, dashboard in dashboards().items():
        for panel in dashboard["panels"]:
            assert panel["type"] in kinds, (name, panel["title"], panel["type"])
            if panel["type"] == "row":
                continue
            unit = panel["fieldConfig"]["defaults"]["unit"]
            assert unit in units, (name, panel["title"], unit)


def test_every_legend_names_a_label_its_query_still_has():
    """`{{transport}}` on a query that summed the label away renders as the
    literal text, on every line of the panel."""
    for name, dashboard in dashboards().items():
        for panel in dashboard["panels"]:
            if panel["type"] == "row":
                continue
            for target in panel["targets"]:
                wanted = set(re.findall(r"\{\{\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\}\}", target["legendFormat"]))
                kept = labels_kept(target["expr"])
                if not wanted or kept is None:
                    continue
                assert wanted <= kept, (name, panel["title"], wanted - kept)


def test_a_row_of_any_size_lays_out():
    """Rendered, not just measured: the crash this covers came from `render`
    zipping a row against widths computed for a different number of panels."""
    module = generator()
    panel = module.graph("One", module.Query("sketchy_rooms_live", "rooms"))
    for count in range(1, 10):
        board = module.Dashboard(
            uid="sketchy-shape",
            title="Shape",
            description="",
            rows=(module.Row("Row", (panel,) * count),),
        )
        drawn = [entry for entry in module.render(board)["panels"] if entry["type"] != "row"]
        assert len(drawn) == count
        cells: set[tuple[int, int]] = set()
        for entry in drawn:
            place = entry["gridPos"]
            assert 0 <= place["x"] and place["x"] + place["w"] <= 24, (count, place)
            covered = {
                (x, y)
                for x in range(place["x"], place["x"] + place["w"])
                for y in range(place["y"], place["y"] + place["h"])
            }
            assert not covered & cells, (count, place)
            cells |= covered


def test_every_panel_has_a_place_of_its_own():
    """Ids unique, nothing off the 24-column grid, no two panels overlapping -
    what Grafana would otherwise silently rearrange on load."""
    for name, dashboard in dashboards().items():
        ids = [panel["id"] for panel in dashboard["panels"]]
        assert len(ids) == len(set(ids)), name
        cells: set[tuple[int, int]] = set()
        for panel in dashboard["panels"]:
            place = panel["gridPos"]
            assert 0 <= place["x"] and place["x"] + place["w"] <= 24, (name, panel["title"])
            covered = {
                (x, y)
                for x in range(place["x"], place["x"] + place["w"])
                for y in range(place["y"], place["y"] + place["h"])
            }
            assert not covered & cells, (name, panel["title"])
            cells |= covered


def test_the_dashboards_read_the_provisioned_datasource():
    """The `datasource` variable defaults to the uid the provisioning file
    gives Prometheus, and every panel and query reads the variable - so a
    provisioned Grafana shows data with nothing chosen by hand, and another
    Prometheus can still be picked."""
    datasources = yaml.safe_load((GRAFANA / "provisioning" / "datasources" / "sketchy.yml").read_text())
    [provisioned] = datasources["datasources"]
    assert provisioned["type"] == "prometheus"
    for name, dashboard in dashboards().items():
        [variable] = [v for v in dashboard["templating"]["list"] if v["name"] == "datasource"]
        assert variable["current"]["value"] == provisioned["uid"], name
        for panel in dashboard["panels"]:
            if panel["type"] == "row":
                continue
            assert panel["datasource"] == {"type": "prometheus", "uid": "${datasource}"}, (name, panel["title"])
            for target in panel["targets"]:
                assert target["datasource"] == panel["datasource"], (name, panel["title"])


def test_the_dashboards_are_provisioned_read_only():
    """A change made in the UI would be lost on the next reload, and would
    drift from the generator until then; refusing it says where to go."""
    providers = yaml.safe_load((GRAFANA / "provisioning" / "dashboards" / "sketchy.yml").read_text())
    [provider] = providers["providers"]
    assert provider["type"] == "file"
    assert provider["allowUiUpdates"] is False
    for name, dashboard in dashboards().items():
        assert dashboard["editable"] is False, name


def test_every_uid_is_unique_and_stable():
    uids = [dashboard["uid"] for dashboard in dashboards().values()]
    assert len(uids) == len(set(uids))
    assert all(uid.startswith("sketchy-") for uid in uids), uids
