"""The dashboards are their generator's output, and name only real series (#968).

A panel whose metric was renamed under it draws an empty graph, and nobody
notices until the day it was needed - the reason R-OBS-13 keeps the alert rules
in the repository, and checks them, applies to a dashboard just the same. So
every query here is held to the same list of sources the alert rules are: the
server's own exposition, the recording rules, the probe's textfile, and the
exporters named once in `test_alert_rules.py`.

The JSON is generated by `ops/grafana/generate.py` and committed; hand-editing
it, or saving it from Grafana's UI, is caught by the first test.
"""
from __future__ import annotations

import importlib.util
import json
from pathlib import Path
import sys

import yaml

from tests.test_alert_rules import (
    EXTERNAL_METRIC,
    EXTERNAL_SERIES,
    METRIC,
    RULE_FILES,
    exposed_names,
    load,
    rule_names,
)

GRAFANA = Path(__file__).resolve().parents[2] / "ops" / "grafana"


def generator():
    name = "sketchy_grafana_generate"
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(name, GRAFANA / "generate.py")
    module = importlib.util.module_from_spec(spec)
    # Registered first: `dataclasses` looks its own module up while building
    # each class, and a file loaded by path is otherwise nowhere to be found.
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def dashboards() -> dict[str, dict]:
    return {path.name: json.loads(path.read_text()) for path in sorted((GRAFANA / "dashboards").glob("*.json"))}


def test_the_committed_dashboards_are_the_generators_output():
    stale = generator().stale()
    assert stale == [], f"regenerate with `python3 ops/grafana/generate.py`: {stale}"


def test_every_series_a_panel_queries_is_one_something_exposes():
    known = exposed_names() | {name for path in RULE_FILES for name in rule_names(load(path))}
    unknown: dict[str, set[str]] = {}
    for dashboard, panel, expr in generator().expressions():
        missing = {metric for metric in METRIC.findall(expr) if metric not in known}
        missing |= {metric for metric in EXTERNAL_METRIC.findall(expr) if metric not in EXTERNAL_SERIES}
        if missing:
            unknown[f"{dashboard} / {panel}"] = missing
    assert unknown == {}, unknown


def test_every_panel_has_a_place_of_its_own():
    """Ids unique, nothing off the 24-column grid, no two panels overlapping -
    what Grafana would otherwise silently rearrange on load."""
    for name, dashboard in dashboards().items():
        ids = [panel["id"] for panel in dashboard["panels"]]
        assert len(ids) == len(set(ids)), name
        cells: set[tuple[int, int]] = set()
        for panel in dashboard["panels"]:
            place = panel["gridPos"]
            assert 0 <= place["x"] and place["x"] + place["w"] <= 24, (name, panel["title"])
            covered = {
                (x, y)
                for x in range(place["x"], place["x"] + place["w"])
                for y in range(place["y"], place["y"] + place["h"])
            }
            assert not covered & cells, (name, panel["title"])
            cells |= covered


def test_the_dashboards_read_the_provisioned_datasource():
    """The `datasource` variable defaults to the uid the provisioning file
    gives Prometheus, and every panel and query reads the variable - so a
    provisioned Grafana shows data with nothing chosen by hand, and another
    Prometheus can still be picked."""
    datasources = yaml.safe_load((GRAFANA / "provisioning" / "datasources" / "sketchy.yml").read_text())
    [provisioned] = datasources["datasources"]
    assert provisioned["type"] == "prometheus"
    for name, dashboard in dashboards().items():
        [variable] = [v for v in dashboard["templating"]["list"] if v["name"] == "datasource"]
        assert variable["current"]["value"] == provisioned["uid"], name
        for panel in dashboard["panels"]:
            if panel["type"] == "row":
                continue
            assert panel["datasource"] == {"type": "prometheus", "uid": "${datasource}"}, (name, panel["title"])
            for target in panel["targets"]:
                assert target["datasource"] == panel["datasource"], (name, panel["title"])


def test_the_dashboards_are_provisioned_read_only():
    """A change made in the UI would be lost on the next reload, and would
    drift from the generator until then; refusing it says where to go."""
    providers = yaml.safe_load((GRAFANA / "provisioning" / "dashboards" / "sketchy.yml").read_text())
    [provider] = providers["providers"]
    assert provider["type"] == "file"
    assert provider["allowUiUpdates"] is False
    for name, dashboard in dashboards().items():
        assert dashboard["editable"] is False, name


def test_every_uid_is_unique_and_stable():
    uids = [dashboard["uid"] for dashboard in dashboards().values()]
    assert len(uids) == len(set(uids))
    assert all(uid.startswith("sketchy-") for uid in uids), uids
