"""Initial schema: config, users, games, word lists

Revision ID: 264a248789d1
Revises: 
Create Date: 2026-08-17 22:22:35.488280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264a248789d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('game_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_name', sa.String(length=64), nullable=False),
    sa.Column('scoring_mode', sa.String(length=16), nullable=False),
    sa.Column('hint_mode', sa.String(length=16), nullable=False),
    sa.Column('drawing_seconds', sa.Integer(), nullable=False),
    sa.Column('total_rounds', sa.Integer(), nullable=False),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=32), nullable=False),
    sa.Column('name_color', sa.String(length=16), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(
            'ix_users_username_lower',
            [sa.text('lower(username)')],
            unique=True,
            sqlite_where=sa.text('username IS NOT NULL'),
            postgresql_where=sa.text('username IS NOT NULL'),
        )

    op.create_table('word_lists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('is_bundled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('word_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_lists_slug'), ['slug'], unique=True)

    op.create_table('game_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('final_rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_participants_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_participants_user_id'), ['user_id'], unique=False)

    op.create_table('round_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('drawer_user_id', sa.String(length=36), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['drawer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['game_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('round_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_round_records_drawer_user_id'), ['drawer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_records_game_id'), ['game_id'], unique=False)

    op.create_table('words',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('word_list_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(length=64), nullable=False),
    sa.Column('offer_count', sa.Integer(), nullable=False),
    sa.Column('pick_count', sa.Integer(), nullable=False),
    sa.Column('correct_guess_count', sa.Integer(), nullable=False),
    sa.Column('total_guesser_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['word_list_id'], ['word_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_list_id', 'text', name='uq_word_list_text')
    )
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_words_word_list_id'), ['word_list_id'], unique=False)

    op.create_table('round_guesses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('round_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('guess_time_seconds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['round_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('round_guesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_round_guesses_round_id'), ['round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_guesses_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round_guesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_round_guesses_user_id'))
        batch_op.drop_index(batch_op.f('ix_round_guesses_round_id'))

    op.drop_table('round_guesses')
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_words_word_list_id'))

    op.drop_table('words')
    with op.batch_alter_table('round_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_round_records_game_id'))
        batch_op.drop_index(batch_op.f('ix_round_records_drawer_user_id'))

    op.drop_table('round_records')
    with op.batch_alter_table('game_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_game_participants_game_id'))

    op.drop_table('game_participants')
    with op.batch_alter_table('word_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_lists_slug'))

    op.drop_table('word_lists')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username_lower')

    op.drop_table('users')
    op.drop_table('game_records')
    op.drop_table('app_config')
    # ### end Alembic commands ###
